### ISSUE TITLE
Sketch up...!

### ISSUE THREAD

**Issue by chattyplatty** [SASDigitalHumanitiesTraining/3D#13]
Hi! I have some queries and I am hoping someone can help...

1) I initially made Valeria Vitale's model with no problems - sketchup is very intuitive.... but.... when I tried to import my own image that I made earlier in the week, this seemed to delete the textures on the walls that I had added. However, when I clicked on the walls themselves, the outline block of the texture remained, but not the wall-painting itself. Can anyone help with where they went?

2) When inputting my own model I really struggled with finding it...to avoid this in future should I be clicking on the model before importing so that it is attached to my cursor on the model, and thus more easy to find in the planes of sketchup?

3) Once imported, my model is enormous, or so it would seem because it is now little more than a dark blob in the building - is there any way I can change this so that it is more clearly visible like the venus ?

4) Finally (and apologies!), I am trying to use the rotate button on sketchup - but I am not quite sure how to work it. Has anyone been able to figure this out?

Many thanks, and apologies for the list!

Hannah

**Comment by LindaStoessel** [comment]
Hi, I can only help with some of your questions:

2. In my experience when importing an own model in sketchup, it is automatically attached tot he cursor.
3. I wondered about that aswell, also mine is not a coloured, solid object...
4. I struggled with that aswell. For me it was easier to use the „move“-button, which gives you options to rotate the object aswell.

**Comment by gabrielbodard** [comment]
> 1. I initially made Valeria Vitale's model with no problems - sketchup is very intuitive.... but.... when I tried to import my own image that I made earlier in the week, this seemed to delete the textures on the walls that I had added. However, when I clicked on the walls themselves, the outline block of the texture remained, but not the wall-painting itself. Can anyone help with where they went?

This sounds like glitchy behaviour rather than than a usual feature that was meant to happen. Perhaps the object overlapped with another, and the software got confused? Sometimes it's easier to delete the affected area and rebuild it, than work out why it's become transparent and/or missing. (As a rule, I try to build or import separate objects further apart, and then move them together once they're ready, so this is less likely to happen.)

**Comment by gabrielbodard** [comment]
> 4. Finally (and apologies!), I am trying to use the rotate button on sketchup - but I am not quite sure how to work it. Has anyone been able to figure this out?

The rotate button is fiddly (primarily because it is designed to work in three dimensions, which makes everything harder to handle on a 2D screen!). I recently started understanding it better when I noticed that there are instructions at the bottom of the screen on what to do with each of three three clicks you need to use 'rotate'. You need to choose the plane of rotation, the point around which you're rotating, and the angle (amount of rotation)—not necessarily in that order, I'm writing from memory…

**Comment by AnnaRuhland** [comment]
Thank you @chattyplatty and @LindaStoessel and @gabrielbodard for asking and answering these questions, I also had problems using the rotation to propperly set my own object, but it is much easier with the move-function. Also, mine is a blueish (when selected) and blackish bobble, anything but a nice, solid object, like the Venus...

I tried to work more on the roofing and totally failed to cutting back the cornice. I think I somehow selected to wrong corners of the rectangles, because I got confused by which one is the "first" and which one is the "second" one in the handout description. I tried different options and it did weird things - none of them did a nice cornice :D 
Does anyone already managed to draw the cornice and can provide me with some tips? Thanks!

**Comment by chattyplatty** [comment]
I'm really struggling with the cornice too - having the same issue with understanding which is first and second as well! So glad I'm not the only one having issues here!! Can anyone help?

**Comment by LindaStoessel** [comment]
I understood it to mean that the first rectangle is the lower one, the second rectangle the upper one. Then following the instruction it worked for me and I think I did the right things...: the "lower surface of the second rectangle" (I had to try things out there aswell, this was a bit confusing) is the lower, horinzontal part of the upper rectangle. I found the "follow me" clicking "tools" and clicked on the small rectangle I created before connecting the upper corners of both the rectangles. This worked. I don't know if these are better instructions than the ones given by Valeria Vitale, sorry!

**Comment by gabrielbodard** [comment]
The cornice is the most difficult and unintuitive part of the whole exercise, and it's very hard to explain it in text alone. I think somewhere we may have a video of Valeria working through this example, which I can look for if anyone still has trouble with this part after trying @LindaStoessel's tips (which sound promising).

(There's no cornice in my current model, but I'll try to find an excuse to do something similar once I'm done tracing my floor-plan in Sketchup…)

**Comment by chattyplatty** [comment]
I have just managed to succeed combining Valeria's worksheet and @LindaStoessel's tips!! Yay!! Thanks all :-)

**Comment by AnnaRuhland** [comment]
Worked out for me as well now in the combination of your tips and Valeria's handout! thanks @LindaStoessel !!!

**Comment by Al-scw** [comment]
> Also, mine is a blueish (when selected) and blackish bobble, anything but a nice, solid object, like the Venus...

I have this issue as well (only seeing the geometry instead of a full mesh with texture), and the solution it seems is to add a plug in that allows you to import obj's with the material and texture files. Unfortunately it is now a feature that you need to sign up for (and pay)

**Comment by gabrielbodard** [comment]
Does the texture not automatically come with an object if you import it as a Collada / .dae file?
