### ISSUE TITLE
No wall textures of Iseum in SketchFab

### ISSUE THREAD

**Issue by chattyplatty** [SASDigitalHumanitiesTraining/3D#16]
Hi! I have just published my [Iseum](https://sketchfab.com/3d-models/iseum-afb059e3cc3b4befbbf7d805574d75f6) in SketchFab, but have realised the wall textures have not come through. Any advice on why this is and whether I can rectify the problem now the model is complete, or would I have to delete all the roof work to reinstall?

Thanks! 
Hannah

**Comment by gabrielbodard** [comment]
This may be the same problem at in [issue 7](https://github.com/SASDigitalHumanitiesTraining/3D/issues/7) and [issue 11](https://github.com/SASDigitalHumanitiesTraining/3D/issues/11)– with the exception that the first solution suggested by Tom (uploading directly from the software) won't work from Sketchup because it doesn't work from the free version.

What format did you export to before uploading to Sketchfab? Does it include the textures in the model (e.g. Collada/.dae), or as a separate jpg? If the latter, you could also zip them up before uploading the Sketchfab, *or* try assigning them manually, as in [this tutorial](https://help.sketchfab.com/hc/en-us/articles/202600873-Materials-and-Textures#textures) that Tom linked us to…

**Comment by chattyplatty** [comment]
I exported into Collada/.dae - so I don't think the zipping would work, but I'll have a look at the tutorial - thanks!

**Comment by gabrielbodard** [comment]
Also just a note that if you did find you wanted to go back and do something inside the house and the roof was in the way, you wouldn't need to delete and rebuild it; just select and "hide" the components you want to temporarily go away (**Edit --> Hide** or ctrl+E), then you can "unhide" them when you're done.

**Comment by thein13** [comment]
I had the same problem with a SketchUp model: all the surface textures disappeared. It was saved as Collada and object file, neither worked. Is there a solution? I did read the other threads, but I couldn't see anything that worked.

P.S. with SketchUp, am I right in thinking it's hard to correct or change things at the end? I did an altar and realised at the end that I'd misread the height measurements. But not sure how I can compress the base once everything else has already been built up.

**Comment by chattyplatty** [comment]
Hi Alex - have a look at the tutorial Gabby mentioned in the thread above. This explains how to add the wall textures once the model is in Sketchfab, and I found it pretty useful!

**Comment by thein13** [comment]
> Hi Alex - have a look at the tutorial Gabby mentioned in the thread above. This explains how to add the wall textures once the model is in Sketchfab, and I found it pretty useful!

Many thanks! I did the zipping (makes sense) and it almost worked. A few of the image/textures were flashing with diagonal lines and almost invisible, so not yet perfect. Pressed all the buttons but nothing changed, but did find the the annotation numbers, which will be great for creating iconography teaching tools.

**Comment by gabrielbodard** [comment]
> P.S. with SketchUp, am I right in thinking it's hard to correct or change things at the end? I did an altar and realised at the end that I'd misread the height measurements. But not sure how I can compress the base once everything else has already been built up.

It's a bit harder, yes. Once an object exists you have to resize it manually, which (as we discussed earlier) is trickier than just typing the dimensions in metres while creating the object. With a built-up object there's the added complication of the added components being (a) in the way of what you want to do, and (b) being attached to those below, so if you  resize the one below, the one above stretches to fill the space rather than moving down.

- Resizing can be dealt with using the tutorial I linked from [this issue](https://github.com/SASDigitalHumanitiesTraining/3D/issues/15#issuecomment-877124380)
- You can make upper features invisible by electing **Edit --> HIde** (shortcut ctrl+E or cmd+E) which makes it easier to deal with the obscuring problem (a)
- If anyone has any ideas for problem (b), short of slicing off a section of the bottom of the altar and then moving the rest down, I'd like to hear it…

(Actually that last option isn't as hard as it sounds, and you can use numbers—rather than dragging—to do it.)

**Comment by thein13** [comment]
> > P.S. with SketchUp, am I right in thinking it's hard to correct or change things at the end? I did an altar and realised at the end that I'd misread the height measurements. But not sure how I can compress the base once everything else has already been built up.
> 
> It's a bit harder, yes. Once an object exists you have to resize it manually, which (as we discussed earlier) is trickier than just typing the dimensions in metres while creating the object. With a built-up object there's the added complication of the added components being (a) in the way of what you want to do, and (b) being attached to those below, so if you resize the one below, the one above stretches to fill the space rather than moving down.
> 
> * Resizing can be dealt with using the tutorial I linked from [this issue](https://github.com/SASDigitalHumanitiesTraining/3D/issues/15#issuecomment-877124380)
> * You can make upper features invisible by electing **Edit --> HIde** (shortcut ctrl+E or cmd+E) which makes it easier to deal with the obscuring problem (a)
> * If anyone has any ideas for problem (b), short of slicing off a section of the bottom of the altar and then moving the rest down, I'd like to hear it…
> 
> (Actually that last option isn't as hard as it sounds, and you can use numbers—rather than dragging—to do it.)

Thank you for the tips!

**Comment by gabrielbodard** [comment]
Pleasure. I tried out the cropping and moving down solution, and it seemed simple enough. Happy to try to make a short demo sometime if that would help.
