### ISSUE TITLE
How do you get rid of the newspaper base of your model?

### ISSUE THREAD

**Issue by chattyplatty** [SASDigitalHumanitiesTraining/3D#8]
Hi! I have managed to build my model and upload to Sketchfab https://sketchfab.com/3d-models/ratty-final-model-3bd608fa4b3b4be08844c459374e9611, but I am keen to find out how to remove the newspaper base on which it sits from the final model. I tried using the circle / rectangular / free form tools in Agisoft but it is very difficult to get a neat line around the model. Is it that I need to photograph the underside of the artefact and then stitch them together? (I **think** something about this was mentioned yesterday). If so, I still think I would have the newspaper layer underneath visible? Or am I missing something? Any help would be greatly appreciated! Thanks, Hannah

**Comment by Al-scw** [comment]
Hi Hannah, sorry that link didn't open, can you share it again?
You are correct that you would need to photograph the underside and align them together (see video tutorial by Samantha Porter); however, if you don't wish to model the underside, you will just have to crop out the newspaper and be left with a hole on the bottom, or fill it to do a flat base. 
If you chose to image the underside, you want to have enough overlap of the two sides so that you can crop off the newspaper on both models and still be left with points that align. Hope that makes sense, but the youtube tutorial should make that more visually clear

**Comment by chattyplatty** [comment]
[https://sketchfab.com/3d-models/ratty-3bd608fa4b3b4be08844c459374e9611?utm_source=triggered-emails&utm_medium=email&utm_campaign=new-model-uploaded](url) - hopefully this link works better? Thanks for the advice, I have just watched the YouTube video - very helpful! Thanks!

**Comment by gabrielbodard** [comment]
@chattyplatty I've edited the link in your issue above so that it works. Not that the syntax for links in Markdown is `[text](link)` – e.g. `[Ratty](https://sketchfab.com/3d-models/ratty-final-model-3bd608fa4b3b4be08844c459374e9611)` will render as [Ratty](https://sketchfab.com/3d-models/ratty-final-model-3bd608fa4b3b4be08844c459374e9611). (Apologies if my demo of this on Monday was unclear.)

To your question, I usually crop off the newspaper etc. in Meshmixer rather than Metashape, as it gives more control over what you're doing. (And also allows you to "fill" the space left behind so there's a flat surface rather than a hole in your model.) With a very flat surface, the command **Edit --> Plane Cut** can work well, but on your model that would probably crop off too much, so try **Select --> Lasso** try draw around bits you want to remove, and delete them bit by bit. (Remember to keep a finger near ctrl+z, as I guarantee it _will_ go wrong!) It'll take a bit of trial and error.

**Comment by chattyplatty** [comment]
Thanks Gabby and Alicia - Really useful, and sorry about the link issue. Will try to remember the specifics of writing links on this issuetracker! Best wishes, Hannah
